---
# Choose endpoint type (this will override the value of clouds.yaml)
endpoint_type: internal
# Ignored when multicloud.enabled: true
cloud: default

replicaCount: 1

image:
  repository: ghcr.io/openstack-exporter/openstack-exporter
  tag: 1.7.0
  pullPolicy: Always

serviceMonitor:
  interval: 1m
  scrapeTimeout: 30s

multicloud:
  # Enable multicloud (i.e. /probe?... targets)
  # Doc: https://github.com/openstack-exporter/openstack-exporter#description
  enabled: true
  # Monitor the exporter's internal metrics (i.e. /metrics)
  selfmonitor: true
  # List of clouds to scrape, and the services to scrape from them
  clouds:
    - name: cloud1
      services:
        - volume
    - name: cloud2
      services:
        - volume
        - image
        - identity
        - compute
        - network
        - placement # NB this needs the openstack-exporter release > 1.4.0

# Add extra args to the exporter.
# Doc: https://github.com/openstack-exporter/openstack-exporter#command-line-options
#extraArgs:
#  - --disable-service.baremetal
#  - --disable-service.container-infra
#  - --disable-service.object-store

# Add extra environment variables
# extraEnvs:
#  "ENV_VAR": "value"

# Add extra labels
#commonLabels:
#  prometheus.io/monitor: "true"

# Generate a secret for clouds.yaml
# Doc: https://github.com/openstack-exporter/openstack-exporter#openstack-configuration
clouds_yaml_config: |
  clouds.yaml: |
      clouds:
        default:
          region_name: your-region-here
          auth:
            username: your-user-here
            password: your-password-here
            project_name: your-project-here
            project_domain_name: 'Default'
            user_domain_name: 'Default'
            auth_url: 'http://your-url-here:5000/v3'
# In case of multicloud.enabled
#        cloud1:
#         ...
#        cloud2:
#         ...

promethuesRules:
  keystone:
    enabled: true
    rules:
    - alert: KeystoneDown
      for: 5m
      expr: openstack_identity_up != 1
      labels:
        severity: critical
      annotations:
        summary: "OpenStack Keystone service down"
        description: "OpenStack Keystone service down"

  glance:
    enabled: true
    rules:
    - alert: GlanceDown
      for: 5m
      expr: openstack_glance_up != 1
      labels:
        severity: critical
      annotations:
        summary: "OpenStack Glance service down"
        description: "OpenStack Glance service down"

  cinder:
    enabled: true
    rules:
    - alert: CinderDown
      for: 5m
      expr: openstack_cinder_up != 1
      labels:
        severity: critical
      annotations:
        summary: "OpenStack Cinder service down"
        description: "OpenStack Cinder service down"

    - alert: CinderAgentDown
      for: 5m
      expr: openstack_cinder_agent_state{adminState="enabled"} != 1
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.hostname}}`}}` `{{`{{$labels.exported_service}}`}}` down"
        description: >
          The service `{{`{{$labels.exported_service}}`}}` running on `{{`{{$labels.hostname}}`}}`
          is being reported as down for 5 minutes. This can affect volume operations so it must
          be resolved as quickly as possible.

    - alert: CinderAgentDisabled
      for: 1h
      expr: openstack_cinder_agent_state{adminState!="enabled"}
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.hostname}}`}}` `{{`{{$labels.exported_service}}`}}` disabled"
        description: >
          The service `{{`{{$labels.exported_service}}`}}` running on `{{`{{$labels.hostname}}`}}`
          has been disabled for 60 minutes. This can affect volume operations so it must be resolved
          as quickly as possible.

    # value = (9 | 10 | 13 | 14 | 15)
    - alert: CinderVolumeInError
      for: 15m
      expr: openstack_cinder_volume_status{status=~"error.*"}
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in ERROR state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.
          It must be cleaned up or removed in order to provide a consistent customer experience.

    - alert: CinderVolumeInCreating
      expr: openstack_cinder_volume_status == 0
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in CREATING state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInReserved
      expr: openstack_cinder_volume_status == 2
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in RESERVED state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInAttaching
      expr: openstack_cinder_volume_status == 3
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in ATTACHING state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 10 minutes.

    - alert: CinderVolumeInDetaching
      expr: openstack_cinder_volume_status == 4
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in DETACHING state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 10 minutes.

    - alert: CinderVolumeInMaintenance
      expr: openstack_cinder_volume_status == 6
      for: 20m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in MAINTENANCE state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInDeleting
      expr: openstack_cinder_volume_status == 7
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in DELETING state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInAwaitingTransfer
      expr: openstack_cinder_volume_status == 8
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in AwaitingTransfer state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInBackingUp
      expr: openstack_cinder_volume_status == 11
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in BackingUp state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInRestoringBackup
      expr: openstack_cinder_volume_status == 12
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in RESTORING-BACKUP state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInDownloading
      expr: openstack_cinder_volume_status == 16
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in DOWNLOADING state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInUploading
      expr: openstack_cinder_volume_status == 17
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in UPLOADING state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInRetyping
      expr: openstack_cinder_volume_status == 18
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in RETYPING state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: CinderVolumeInExtending
      expr: openstack_cinder_volume_status == 19
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Volume in EXTENDING state"
        description: >
          The volume `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

  neutron:
    enabled: true
    rules:
    - alert: NeutronDown
      for: 5m
      expr: openstack_neutron_up != 1
      labels:
        severity: critical
      annotations:
        summary: "OpenStack Neutron service down"
        description: "OpenStack Neutron service down"

    - alert: NeutronAgentDown
      for: 5m
      expr: openstack_neutron_agent_state{adminState="up"} != 1
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.hostname}}`}}` `{{`{{$labels.exported_service}}`}}` down"
        description: >
          The service `{{`{{$labels.exported_service}}`}}` running on `{{`{{$labels.hostname}}`}}`
          is being reported as down for 5 minutes. This can affect network operations so it must
          be resolved as quickly as possible.

    - alert: NeutronAgentDisabled
      for: 1h
      expr: openstack_neutron_agent_state{adminState!="up"}
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.hostname}}`}}` `{{`{{$labels.exported_service}}`}}` disabled"
        description: >
          The service `{{`{{$labels.exported_service}}`}}` running on `{{`{{$labels.hostname}}`}}`
          has been disabled for 60 minutes. This can affect network operations so it must be resolved
          as quickly as possible.

    - alert: NeutronBindingFailedPorts
      expr: openstack_neutron_port{binding_vif_type="binding_failed"} != 0
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.device_owner}}`}}` `{{`{{$labels.mac_address}}`}}` binding failed"
        description: >
          The NIC `{{`{{$labels.mac_address}}`}}` of `{{`{{$labels.device_owner}}`}}`
          has binding failed port now.

    - alert: NeutronNetworkOutOfIPs
      expr: |
        sum by (network_id) (openstack_neutron_network_ip_availabilities_used{project_id!=""}) / sum by (network_id) (openstack_neutron_network_ip_availabilities_total{project_id!=""}) * 100 > 80
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.network_name}}`}}` `{{`{{$labels.subnet_name}}`}}` running out of IPs"
        description: >
          The subnet `{{`{{$labels.subnet_name}}`}}` within `{{`{{$labels.network_name}}`}}`
          is currently at `{{`{{$value}}`}}`% utilization. If the IP addresses run out, it will
          impact the provisioning of new ports.

  nova:
    enabled: true
    rules:
    - alert: NovaDown
      for: 5m
      expr: openstack_nova_up != 1
      labels:
        severity: critical
      annotations:
        summary: "OpenStack Nova service down"
        description: "OpenStack Nova service down"

    - alert: NovaAgentDown
      for: 5m
      expr: openstack_nova_agent_state{adminState="enabled"} != 1
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.hostname}}`}}` `{{`{{$labels.exported_service}}`}}` down"
        description: >
          The service `{{`{{$labels.exported_service}}`}}` running on `{{`{{$labels.hostname}}`}}`
          is being reported as down. This can affect compute operations so it must be resolved
          as quickly as possible.

    - alert: NovaAgentDisabled
      for: 1h
      expr: openstack_nova_agent_state{adminState!="enabled"}
      labels:
        severity: warning
      annotations:
        summary: "`{{`{{$labels.hostname}}`}}` `{{`{{$labels.exported_service}}`}}` disabled"
        description: >
          The service `{{`{{$labels.exported_service}}`}}` running on `{{`{{$labels.hostname}}`}}`
          has been disabled for 60 minutes. This can affect compute operations so it must be resolved
          as quickly as possible.

    - alert: NovaInstanceInError
      for: 10m
      expr: openstack_nova_server_status{status="ERROR"}
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Instance in `{{`{{$labels.status}}`}}` state"
        description: >
          The instance `{{`{{$labels.id}}`}}` on host `{{`{{$labels.hypervisor_hostname}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 10 minutes.
          It must be cleaned up or removed in order to provide a consistent customer experience.

    - alert: NovaInstanceInBuilding
      for: 15m
      expr: openstack_nova_server_status == 1
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Instance in `{{`{{$labels.status}}`}}` state"
        description: >
          The instance `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: NovaInstanceInRESIZE
      for: 15m
      expr: openstack_nova_server_status == 10
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Instance in `{{`{{$labels.status}}`}}` state"
        description: >
          The instance `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: NovaInstanceInUNKNOWN
      for: 15m
      expr: openstack_nova_server_status == 13
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Instance in `{{`{{$labels.status}}`}}` state"
        description: >
          The instance `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: NovaInstanceInVERIFY_RESIZE
      for: 15m
      expr: openstack_nova_server_status == 14
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Instance in `{{`{{$labels.status}}`}}` state"
        description: >
          The instance `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 15 minutes.

    - alert: NovaInstanceInMIGRATING
      for: 30m
      expr: openstack_nova_server_status == 15
      labels:
        severity: critical
      annotations:
        summary: "`{{`{{$labels.name}}`}}` Instance in `{{`{{$labels.status}}`}}` state"
        description: >
          The instance `{{`{{$labels.id}}`}}` has been in `{{`{{$labels.status}}`}}` state for over 30 minutes.

    - alert: NovaFailureRisk
      for: 6h
      expr: |
        (sum(openstack_nova_memory_available_bytes-openstack_nova_memory_used_bytes) - max(openstack_nova_memory_used_bytes)) / sum(openstack_nova_memory_available_bytes-openstack_nova_memory_used_bytes) * 100 < 0.25
      labels:
        severity: warning
      annotations:
        summary: "[nova] Failure risk"
        description: >
          The cloud capacity will be at `{{`{{$value}}`}}` in the event of the failure of a single
          hypervisor which puts the cloud at risk of not being able to recover should any hypervisor
          failures occur. Please ensure that adequate amount of infrastructure is assigned to this
          deployment to prevent this.

    - alert: NovaCapacityNearFull
      for: 6h
      expr: |
        sum (
            openstack_nova_memory_used_bytes
          + on(hostname) group_left(adminState)
            (0 * openstack_nova_agent_state{exported_service="nova-compute",adminState="enabled"})
        ) / sum (
            openstack_nova_memory_available_bytes
          + on(hostname) group_left(adminState)
            (0 * openstack_nova_agent_state{exported_service="nova-compute",adminState="enabled"})
        ) * 100 > 75
      labels:
        severity: warning
      annotations:
        summary: "[nova] near full Capacity risk"
        description: >
          The cloud capacity is currently at `{{`{{$value}}`}}` which means there is a risk of running
          out of capacity due to the timeline required to add new nodes.  Please ensure that adequate
          amount of infrastructure is assigned to this deployment to prevent this.

    - alert: NovaCapacityFull
      for: 6h
      expr: |
        sum (
            openstack_nova_memory_used_bytes
          + on(hostname) group_left(adminState)
            (0 * openstack_nova_agent_state{exported_service="nova-compute",adminState="enabled"})
        ) / sum (
            openstack_nova_memory_available_bytes
          + on(hostname) group_left(adminState)
            (0 * openstack_nova_agent_state{exported_service="nova-compute",adminState="enabled"})
        ) * 100 > 85
      labels:
        severity: critical
      annotations:
        summary: "[nova] Capacity risk"
        description: >
          The cloud capacity is currently at `{{`{{$value}}`}}` which means there is a risk of running
          out of capacity due to the timeline required to add new nodes. Please ensure that adequate
          amount of infrastructure is assigned to this deployment to prevent this.

  octavia:
    enabled: true
    rules:
    - alert: LoadbalancerDown
      for: 5m
      expr: openstack_loadbalancer_up != 1
      labels:
        severity: critical
      annotations:
        summary: "OpenStack loadbalancer service down"
        description: "OpenStack loadbalancer service down"

    - alert: LoadbalancerNotActive
      for: 5m
      expr: openstack_loadbalancer_loadbalancer_status{provisioning_status!="ACTIVE"}
      labels:
        severity: critical
      annotations:
        summary: "OpenStack loadbalancer `{{`{{$labels.name}}`}}` provisioning status is not ACTIVE"
        description: "OpenStack loadbalancer `{{`{{$labels.id}}`}}` provisioning status is `{{`{{$labels.provisioning_status}}`}}`"

    - alert: LoadbalancerPoolNotActive
      for: 5m
      expr: openstack_loadbalancer_pool_status{provisioning_status!="ACTIVE"}
      labels:
        severity: critical
      annotations:
        summary: "OpenStack loadbalancer pool `{{`{{$labels.name}}`}}` provisioning status is not ACTIVE"
        description: "OpenStack loadbalancer pool `{{`{{$labels.id}}`}}` provisioning status is `{{`{{$labels.provisioning_status}}`}}`"

  manila:
    enabled: true
    rules:
    - alert: ManilaDown
      for: 5m
      expr: openstack_sharev2_up != 1
      labels:
        severity: critical
      annotations:
        summary: "OpenStack shared file system (Manila) service down"
        description: "OpenStack shared file system (Manila) service down"

    - alert: ManilaStatusNotActive
      for: 5m
      expr: openstack_sharev2_share_status{status!="available"}
      labels:
        severity: critical
      annotations:
        summary: "OpenStack Share `{{`{{$labels.name}}`}}` status is not ACTIVE"
        description: "OpenStack Share `{{`{{$labels.id}}`}}` status is `{{`{{$labels.status}}`}}`"
